<?php
/**
 * Created by PhpStorm.
 * User: mburakergenc
 * Date: 7/15/16
 * Time: 12:26 PM
 */

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository implements UserLoaderInterface
{
    public function loadUserByUsername($id)
    {
        return $this->createQueryBuilder('e')
            ->select('e')
            ->where('e.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }

}
