# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            id: md5encoderservice

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        db_provider:
            entity:
                class: AppBundle:User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: /
                check_path: /
                csrf_parameter: _csrf_security_token
                csrf_token_id: a_private_string
            pattern:    ^/
            http_basic: ~
            provider: db_provider
            logout:
                path: /logout
                target: /
            remember_me:
                secret: '%secret'
                lifetime: 604800 #1week
                path: /
    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: ^/admin, roles: ROLE_ADMIN}
            - { path: ^/users, roles: ROLE_ADMIN}
            - { path: ^/event, roles: ROLE_ADMIN}
            - { path: ^/dashboard, roles: ROLE_USER }

    access_denied_url: /
    role_hierarchy:
        ROLE_ADMIN:         [ROLE_ORGANIZER, ROLE_USER]
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
