# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    personservice:
        class:  AppBundle\Services\PersonService
        arguments: [ "@doctrine.orm.entity_manager" ]

    md5encoderservice:
        class:  AppBundle\Services\Md5PasswordEncoderService

    # event service
    eventservice:
            class:  AppBundle\Services\EventService
            arguments: [ "@doctrine.orm.entity_manager" ]

    # user service
    userservice:
            class: AppBundle\Services\UserService
            arguments: [ "@doctrine.orm.entity_manager" ]

    # attendee service
    attendeeservice:
            class: AppBundle\Services\AttendeeService
            arguments: [ "@doctrine.orm.entity_manager" ]

    # logger service
    myloggerhandler:
        class:  AppBundle\Handler\LogHandler
        arguments: [ "@service_container" ]

    # session log has line formatter
    monolog.formatter.session_request:
          class: Monolog\Formatter\LineFormatter
          arguments:
              - "[%%datetime%%] [%%extra.token%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"

    # session log record is processed in SessionRequestProcessor class
    monolog.processor.session_request:
          class: AppBundle\Processor\SessionRequestProcessor
          arguments:  ['@session']
          tags:
              - { name: monolog.processor, method: processRecord }